### ISSUE TITLE
Node failed to run "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by izuolan** [vcashorg/vcash#2]
**Describe the bug**
Download the latest release can not running:

```shell
~/.vcash# vcash server config
vcash-server.toml file configured and created in current directory

~/.vcash# vcash
Illegal instruction (core dumped)

~/.vcash# vcash server run
Illegal instruction (core dumped)
```

log file:

```shell
cat vcash-server.log
20190521 13:46:04.633 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190521 13:46:04.633 INFO grin_servers::grin::server - Starting server, genesis block: 569ed9e4a546
20190521 13:47:09.854 INFO grin_util::logger - log4rs is initialized, file level: Info, stdout level: Warn, min. level: Info
20190521 13:47:09.854 INFO grin_servers::grin::server - Starting server, genesis block: 569ed9e4a546
20190521 13:47:09.915 ERROR grin_util::logger -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner:

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::h172f6ecc36432f56 (0x55b15a08ba20)
   1: std::panicking::rust_panic_with_hook::h744417edfe714d72 (0x55b15a1d60d9)
             at src/libstd/panicking.rs:482
   2: std::panicking::continue_panic_fmt::h3557b3c3fa21b47b (0x55b15a1d5b81)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x55b15a1d5a65)
             at src/libstd/panicking.rs:312
   4: core::panicking::panic_fmt::h74ee8034b317ceed (0x55b15a1f506c)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h65971818d8111f2c (0x55b1598e2969)
   6: vcash::cmd::server::start_server::h993074add22ebffe (0x55b1598e903b)
   7: vcash::cmd::server::server_command::h19b3c07a95fee415 (0x55b1598e98a0)
   8: vcash::real_main::h0dff9e28d2edf948 (0x55b15990ed9e)
   9: vcash::main::hb1b178db5a5dd3d6 (0x55b15990d0b5)
  10: std::rt::lang_start::{{closure}}::hc8c7474f4e2b44b4 (0x55b1598feff2)
  11: std::rt::lang_start_internal::{{closure}}::h8ad4264c6b68797c (0x55b15a1d5a02)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h7a0381557c6c2cee
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic (0x55b15a1e08e9)
             at src/libpanic_unwind/lib.rs:92
  13: std::panicking::try::h72cb0fef6e9c0ab1 (0x55b15a1d6555)
             at src/libstd/panicking.rs:276
      std::panic::catch_unwind::hbff071ae76e6f224
             at src/libstd/panic.rs:388
      std::rt::lang_start_internal::he0d8d06abc6f912f
             at src/libstd/rt.rs:48
  14: main (0x55b15990f7e1)
  15: __libc_start_main (0x7ff1f60bb82f)
  16: _start (0x55b1598701b8)
  17: <unknown> (0x0)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04/18.04/19.04, Debian stable.
 - Vcash Version 1.0.3
 - Run in Docker container.

Dockerfile:

```
FROM ubuntu:18.04
RUN apt update && apt install wget tar -y && \
    cd /tmp && \
    wget https://github.com/vcashorg/vcash/releases/download/v1.0.3/vcash-v1.0.3-linux-amd64.tgz && \
    tar zxvf /tmp/vcash-v1.0.3-linux-amd64.tgz -C /bin/ && \
    rm /tmp/vcash-v1.0.3-linux-amd64.tgz

VOLUME ["/root/.vcash"]

CMD ["vcash"]
```

**Comment by izuolan** [comment]
Build from source, work fine.

docker build -t vcash -f etc/Dockerfile .
